name: pyhwloc CI

on: [push]

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  lint:
    name: Format and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install packages
      run: |
        python3 -m pip install black isort mypy
    - name: Run lint
      run: |
        black --check .
        isort --profile=black --check .
        mypy .

  Linux-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'fales'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: dev/pyhwloc_dev.yml
        miniforge-version: latest
        activate-environment: pyhwloc_dev
    - name: Install hwloc
      shell: bash -l {0}
      run: |
        # -- Install the latest hwloc
        git clone https://github.com/open-mpi/hwloc.git
        cd hwloc                # pyhwloc/hwloc
        ./autogen.sh
        ./configure --prefix=$CONDA_PREFIX --enable-doxygen
        make -j$(nproc) install

    - name: Build doxygen XML
      shell: bash -el {0}
      run: |
        echo $(pwd)
        cd ./hwloc/doc          # pyhwloc/hwloc/doc
        HWLOC_DOXYGEN_GENERATE_XML=YES doxygen ./doxygen.cfg

    - name: Install pyhwloc editable
      shell: bash -el {0}
      run: |
        echo $(pwd)
        pip install -e . --no-deps --no-build-isolation
        python -c "import pyhwloc"
        git clean -xdf

    - name: Install pyhwloc with wheel
      shell: bash -el {0}
      run: |
        echo $(pwd)
        pip wheel . --no-build-isolation
        pip install pyhwloc-*.whl

    - name: Run tests
      shell: bash -el {0}
      run: |
        pytest -s -v ./pyhwloc/tests

    - name: Build document
      shell: bash -el {0}
      run: |
        echo $(pwd)
        cd docs
        PYHWLOC_XML_PATH=$(pwd)/../hwloc/doc/doxygen-doc/xml make html
