name: pyhwloc CI

on: [push]

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  lint:
    name: Format and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install packages
      run: |
        python3 -m pip install black isort mypy
    - name: Run lint
      run: |
        black --check .
        isort --profile=black --check .
        mypy .

  Linux-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    container:
      image: ghcr.io/trivialfis/pyhwloc:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PYHWLOC }}
    steps:
    - name: Trust git cloning project sources
      run: |
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"

    - name: Install hwloc
      shell: bash -el {0}
      run: |
        echo $(pwd)
        cd /ws/hwloc/
        make install
        cd /ws

    - uses: actions/checkout@v4
      with:
        submodules: false

    - name: Install pyhwloc editable
      shell: bash -el {0}
      run: |
        echo $(pwd)
        pip install -e . --no-deps --no-build-isolation
        python -c "from pyhwloc import Topology"
        git clean -xdf
        pip uninstall pyhwloc -y

    - name: Install pyhwloc from sdist
      shell: bash -el {0}
      run: |
        echo $(pwd)
        python -m build . --sdist
        pip install dist/pyhwloc-*.tar.gz --no-build-isolation
        python -c "from pyhwloc import Topology"
        rm -rf ./dist && git clean -xdf
        pip uninstall pyhwloc -y

    - name: Install pyhwloc with wheel
      shell: bash -l {0}
      run: |
        echo $(pwd)
        echo "conda: ${CONDA_PREFIX}"
        pip wheel -v . --no-build-isolation --wheel-dir dist/
        pip install dist/pyhwloc-*.whl
        python -c "from pyhwloc import Topology"
        rm -rf ./dist && git clean -xdf
        pip uninstall pyhwloc -y

    - name: Install pyhwloc with custom hwloc
      shell: bash -l {0}
      run: |
        echo $(pwd)
        echo "conda: ${CONDA_PREFIX}"
        pip wheel -v . --config-settings=fetch-hwloc=True --wheel-dir dist/
        pip install dist/pyhwloc-*.whl
        python -c "from pyhwloc import Topology"
        git clean -xdf

        python dev/check_plugins.py

    - name: Upload binary wheel
      uses: actions/upload-artifact@v4
      with:
        name: Fat wheel
        path: dist/pyhwloc-*.whl
        if-no-files-found: error
        retention-days: 7

    - name: Run tests
      shell: bash -el {0}
      run: |
        echo $(pwd)
        pytest -s -v -rxXs --durations=0 ./tests

    - name: Build document
      shell: bash -el {0}
      run: |
        echo $(pwd)
        cd docs
        # Path is set by the install_hwloc.sh script.
        PYHWLOC_XML_PATH=/ws/xml make html

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
      with:
        path: docs/build/html
