name: pyhwloc CI

on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  lint:
    name: Format and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'fales'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install packages
      run: |
        python3 -m pip install black isort mypy
    - name: Run lint
      run: |
        black --check .
        isort --profile=black --check .
        mypy .
